-- Buganda clan seed data
-- Run this after the clans table exists to ensure the clan list used by the app is present.

INSERT INTO clans (name, totem) VALUES
('Abalangira', 'Tewali muziro (Royal Clan)'),
('Abalangira b''Essanje', 'Essanje'),
('Ababiito b''Ekooki', 'Mazzi ga Kisasi'),
('Ababiito b''Ekibulala', 'Ekibulala'),
('Butiko', 'Obutiko (ekika ky''obumyu)'),
('Ffumbe', 'Ffumbe'),
('Kiwere', 'Kiwere'),
('Kinyomo', 'Kinyomo'),
('Kayozi', 'Kayozi'),
('Kasimba', 'Kasimba'),
('Lugave', 'Engave'),
('Mpologoma', 'Mpologoma (empologoma)'),
('Mmamba Gabunga', 'Mmamba'),
('Mmamba Kakoboza', 'Mmamba'),
('Mpeewo', 'Mpeewo'),
('Mbwa', 'Mbwa'),
('Mbogo', 'Mbogo'),
('Mutima Omuyanja', 'Mutima Omuyanja'),
('Mutima Omusagi', 'Mutima Omusagi'),
('Musu', 'Musu'),
('Mbuzi', 'Mbuzi'),
('Kkobe', 'Kkobe'),
('Nkerebwe', 'Nkerebwe'),
('Namungoona', 'Namungoona'),
('Nkula', 'Nkula'),
('Ntalaganya', 'Ntalaganya'),
('Ngabi Ensamba', 'Ngabi'),
('Ngabi Ennyunga', 'Ngabi'),
('Ngeye', 'Ngeye'),
('Ngo', 'Ngo'),
('Nggonge', 'Nggonge'),
('Nkima', 'Nkima'),
('Njovu', 'Njovu'),
('Nsuma', 'Nsuma'),
('Nkejje', 'Nkejje'),
('Nnyonyi Nnyange', 'Ennyange'),
('Nvubu', 'Nvubu'),
('Nsunu', 'Nsunu'),
('Nkusu', 'Nkusu'),
('Nvuma', 'Nvuma'),
('Nte', 'Nte'),
('Nseenene', 'Nseenene'),
('Nswaswa', 'Nswaswa'),
('Ndiga', 'Ndiga'),
('Nakinsige', 'Nakinsige'),
('Njaza', 'Njaza'),
('Ngali', 'Ngali'),
('Kibe', 'Kibe'),
('Mazzi ga Kisasi', 'Mazzi ga Kisasi'),
('Mpindi', 'Mpindi'),
('Lukato', 'Lukato'),
('Ndiisa', 'Ndiisa'),
('Nkebuka', 'Nkebuka'),
('Kasanke', 'Kasanke'),
('Kibuba', 'Kibuba')
AS new_clans
ON DUPLICATE KEY UPDATE
  totem = new_clans.totem;

SELECT COUNT(*) AS clan_count FROM clans;