-- Buganda clan seed data
-- Run this after the clans table exists to ensure the clan list used by the app is present.

INSERT INTO clans (name, totem) VALUES
('Abalangira (Royal Clan)', NULL),
('Babiito–Kooki', NULL),
('Babiito–Kibulala', NULL),
('Babiito–Kiziba', NULL),
('Butiko', NULL),
('Ffumbe', NULL),
('Kasanke', NULL),
('Kasimba', NULL),
('Kayozi', NULL),
('Kibe', NULL),
('Kibuba', NULL),
('Kinyomo', NULL),
('Kiwere', NULL),
('Kkobe', NULL),
('Lugave', NULL),
('Lukato', NULL),
('Mazzi ga Kisasi', NULL),
('Mbogo', NULL),
('Mbuzi', NULL),
('Mbwa', NULL),
('Mmamba Gabunga', NULL),
('Mmamba Kakoboza', NULL),
('Mpeewo', NULL),
('Mpindi', NULL),
('Mpologoma', NULL),
('Musu', NULL),
('Mutima Musagi', NULL),
('Mutima Omuyanja', NULL),
('Nakinsige', NULL),
('Ndiga', NULL),
('Ndiisa', NULL),
('Ngabi Nnyunga', NULL),
('Ngabi Nsamba', NULL),
('Ngeye', NULL),
('Ngo', NULL),
('Njaza', NULL),
('Njovu', NULL),
('Nkebuka', NULL),
('Nkejje', NULL),
('Nkerebwe', NULL),
('Nkima', NULL),
('Nkula', NULL),
('Namuŋŋoona', NULL),
('Nnyonyi Nnyange', NULL),
('Nseenene', NULL),
('Nsuma', NULL),
('Nsunu', NULL),
('Nswaswa', NULL),
('Ntalaganya', NULL),
('Nte', NULL),
('Nvubu', NULL),
('Nvuma', NULL),
('Ŋŋaali (Ngaali)', NULL),
('Ŋŋonge (Ngonge)', NULL)
AS new_clans
ON DUPLICATE KEY UPDATE
  totem = new_clans.totem;

SELECT COUNT(*) AS clan_count FROM clans;